pull_request_rules:

  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - status-success=lint
      - status-success=test (16)
    actions:
      merge:
        method: squash
